networks:
  inception_net:
    name: inception_net
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - inception_net

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - inception_net
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - inception_net
    env_file:
      - .env
    secrets:
      - credentials
      - db_password

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: home/arosas-j/data/mysql
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: home/arosas-j/data/wordpress
      o: bind

secrets:
  credentials:
    file: ../secrets/credentials.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt